server:
  port: 5000

product:
  api:
    base-url: http://localhost:3001
    timeout-seconds: 2

spring:
  application:
    name: similar-products
  webflux:
    base-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
